book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_access.urls')),
    path('book_management/', include('book_inventory_management.urls')),
    path('logout/', auth_views.LogoutView.as_view(), {'template_name': 'login.html'}, name='logout'),

]

user_access/urls.py
from django.urls import path

from user_access.views import *
app_name = "user_access"
urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterUserView.as_view(), name='register'),
]

user_access/models.py
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from book_store.utils import generate_slug


class UserCustomManager(BaseUserManager):
    """
    Custom user manager model
    """
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)

        user.save(using=self._db)
        user.slug = generate_slug('user' + str(user.pk))
        user.authentication_key = generate_slug('user' + str(user.pk))
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    objects = UserCustomManager()
    first_name = models.CharField(max_length=45, blank=True, null=True)
    last_name = models.CharField(max_length=45, blank=True, null=True)
    email = models.CharField(unique=True, max_length=255, blank=True, null=True)
    slug = models.SlugField(max_length=255, auto_created=True, editable=False)
    is_staff = models.BooleanField(
        default=False,
        help_text=_('Designates whether the user can log into this admins site.'),
    )
    is_superuser = models.BooleanField(
        default=False,
        help_text=_('Designates whether the user can log into this admins site.'),
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    is_verified = models.BooleanField(
        default=False,
        help_text=_(
            'Designates whether this user has verified email/mobile. '

        ),
    )
    creation_timestamp = models.DateTimeField(_('Creation timestamp'), null=True, blank=True,
                                              auto_now=True)
    created_by = models.ForeignKey('self', on_delete=models.CASCADE, related_name="user_create_by_rel", null=True,
                                   blank=True)

    USERNAME_FIELD = 'email'

    def __str__(self):
        return str(self.get_full_name())

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        if self.last_name:
            full_name = '%s %s' % (self.first_name, self.last_name)
        else:
            full_name = '%s' % self.first_name
        return full_name.strip()

user_access/forms.py
from django import forms
from django.contrib.auth import authenticate

from book_store.utils import validate_email
from user_access.models import User


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for i in self.fields:
            self.fields['email'].error_messages['required'] = 'Email is required'
            self.fields['password'].error_messages['required'] = 'Password is required'

    def clean_password(self):
        email = self.cleaned_data.get('email').lower()
        password = self.cleaned_data.get('password')
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("Invalid email or password")
            if not user.is_active:
                raise forms.ValidationError("Invalid login")
        else:
            raise forms.ValidationError("Email and Password required")
        return password


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            email = email.lower()
            email_valid = validate_email(email)
            if not email_valid:
                raise forms.ValidationError('Invalid Email')
            email = email.strip()
            if User.objects.filter(email__iexact=email).exists():
                if self.instance.email:
                    if self.instance.email.lower() == email.lower():
                        pass
                    else:
                        raise forms.ValidationError('Email Already exists')
                else:
                    raise forms.ValidationError('Email Already exists')
        else:
            raise forms.ValidationError('Email is required')

        return email

user_access/views.py
import json

from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView

from user_access.forms import LoginForm, RegisterForm


class LoginView(TemplateView):
    """
    View for login into the application
    """
    template_name = 'login.html'

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(LoginView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        login_form = LoginForm()
        try:
            if request.user.is_authenticated:
                return HttpResponseRedirect(reverse('book_inventory_management:book_management'))
            else:
                context = {
                    'form': login_form
                }
                return render(request, 'login.html', context)
        except:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')
        login_form = LoginForm(request.POST)
        print(login_form.is_valid(), "dasdasdas")
        if login_form.is_valid():
            user = authenticate(request, email=email, password=password)
            print(user,"sssssssssssss")
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('book_inventory_management:book_list'))
        context = {
            'form': login_form
        }
        return render(request, 'login.html', context)


class RegisterUserView(TemplateView):
    """
    View for register into the application
    """
    template_name = 'register.html'

    @csrf_exempt
    def dispatch(self, *args, **kwargs):
        return super(RegisterUserView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        register_form = RegisterForm()
        context = {
            'form': register_form
        }
        return render(request, 'register.html', context)

    def post(self, request, *args, **kwargs):
        response_data ={'status':True}
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_obj = register_form.save()
            if request.POST.get('password'):
                user_obj.set_password(request.POST.get('password'))
                user_obj.save()
        else:
            response_data['status'] = False
            response_data['errors'] = register_form.errors
        return HttpResponse(json.dumps(response_data), content_type="application/json")

user_access/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Book Inventory</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/ionicons/css/ionicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/typicons/src/font/typicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/shared/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
               {% if form.errors %}
                        <div class="col-sm -12">
                            <div class="alert alert-sm alert-danger alert-dismissible" role="alert">
                               <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                               <i class="fa fa-exclamation-circle"></i><strong>Error!</strong> {{form.password.errors.0}}
                            </div>
                      </div>
                        {%endif%}
                         {% if message %}
                        <div class="col-sm -12">
                            <div class="alert alert-sm alert-danger alert-dismissible mr-1" role="alert">
                               <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                               {{message}}
                            </div>
                      </div>
                        {%endif%}
              <div class="auto-form-wrapper">
                <form action="{% url 'user_access:login' %}" id="loginForm" method="post">
                  <div class="form-group">
                    <label class="label">Username</label>
                    <div class="input-group">
                      <input type="text" class="form-control" name="email" placeholder="Username">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="label">Password</label>
                    <div class="input-group">
                      <input type="password" name="password" class="form-control" placeholder="*********">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary submit-btn btn-block">Login</button>
                    <a href="{% url 'user_access:register' %}" class="btn btn-success submit-btn btn-block">Register</a>
                  </div>
                </form>
              </div>

            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'assets/vendors/js/vendor.bundle.addons.js' %}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/shared/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/shared/misc.js' %}"></script>
    <!-- endinject -->
  </body>
</html>

user_access/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Book Inventory</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/ionicons/css/ionicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/typicons/src/font/typicons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.addons.css' %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static 'assets/css/shared/style.css' %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth auth-bg-1 theme-one">
          <div class="row w-100">
            <div class="col-lg-4 mx-auto">
              <div class="auto-form-wrapper">
                <form id="registerForm" class="registerForm" method="post">
                  <div class="form-group">
                    <label class="label">First Name</label>
                    <div class="input-group">
                      <input type="text" class="form-control required" name="first_name" placeholder="First Name">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                      <span class="error_span"></span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="label">Last Name</label>
                    <div class="input-group">
                      <input type="text" class="form-control required" name="last_name" placeholder="Last Name">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                      <span class="error_span"></span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="label">Email</label>
                    <div class="input-group">
                      <input type="text" class="form-control required" name="email" placeholder="Username">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                      <span class="error_span"></span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="label">Password</label>
                    <div class="input-group">
                      <input type="password" name="password" class="form-control required" placeholder="*********">
                      <div class="input-group-append">
                        <span class="input-group-text">
                          <i class="mdi mdi-check-circle-outline"></i>
                        </span>
                      </div>
                      <span class="error_span"></span>
                    </div>
                  </div>
                  <div class="form-group">
                    <button type="button" class="register_user btn btn-primary submit-btn btn-block">Register</button>
                    <a href="{% url 'user_access:login' %}" class="btn btn-success submit-btn btn-block">Login</a>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'assets/vendors/js/vendor.bundle.addons.js' %}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/shared/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/shared/misc.js' %}"></script>
    <!-- endinject -->
  <script>
  var req = null;
    		$(document).on('click','.register_user',function(){
		$('.register_user').prop('disabled',true)
		$('.error').remove()
		var data = new FormData($('.registerForm').get(0));
		flag = validateForm($('.registerForm :input'))
		data.append('csrfmiddlewaretoken',"{{csrf_token}}")
		if (req != null) req.abort();
		if(flag){
         req = $.ajax({
            type: "POST",
            url : "{% url 'user_access:register' %}",
            data: data,
            processData: false,
            contentType: false,
            success: function(data) {
            	$('.register_user').prop('disabled',false)
                if(data.status == true){
                    $('#registerForm')[0].reset()
                     alert("User Successfully Registered")

                }
                else{
                    console.log(data.errors)
                    var $inputs = $('.registerForm :input');
                    console.log($inputs)
                    $.each(data.errors, function( name, value )  {
                       $inputs.each(function(index, dom){
                           current_name = dom.name;
                           if (current_name == name){
                                  var $error_section = $(this).closest("div").find('.error_span');
                                  $error_section.html("<p class='error'>"+value+"</p>");

                           }
                       });
                    });
                }
            }
        });
        }
        else{
          $('.register_user').prop('disabled',false)
        }
		})

function validateForm(form_inputs)
{
    flag =true
    var $inputs = form_inputs
    $inputs.each(function(index, dom){
          var $error_section = $(this).closest("div").find('span');
          if(($(this).val() == "")&& $(this).hasClass('required')&&$(this).is(':visible')){
            flag = false
                        console.log($error_section.length)
                        console.log($(this).closest("div").find('.error_span'))

                  $error_section.html("<p class='error'>This field is required</p>");
              }
              else
              {
                 //$error_section.html("")
              }

   });
   return flag
}

  </script>
  </body>
</html>