book_inventory_management/urls.py
from django.urls import path

from book_inventory_management.views import *
app_name = "book_inventory_management"
urlpatterns = [
    path('view', BookListView.as_view(), name='book_list'),
    path('update', UpdateInventory.as_view(), name='update_inventory'),
]

book_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_access.urls')),
    path('book_management/', include('book_inventory_management.urls')),
    path('logout/', auth_views.LogoutView.as_view(), {'template_name': 'login.html'}, name='logout'),

]

book_inventory_management/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

# Create your models here.
from user_access.models import User


class BookInventoryDetail(models.Model):
    book_name = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    total_book_count = models.IntegerField(blank=True, null=True)
    book_borrowed = models.IntegerField(blank=True, null=True)
    book_available = models.IntegerField(blank=True, null=True)
    creation_timestamp = models.DateTimeField(_('Creation timestamp'), null=True, blank=True,
                                              auto_now=True)
    slug = models.SlugField(max_length=255, auto_created=True, editable=False)
    status = models.BooleanField(default=True)


class BookBorrowDetail(models.Model):
    book = models.ForeignKey(BookInventoryDetail, on_delete=models.CASCADE,
                             related_name="book_borrow_rel",
                             null=True,
                             blank=True)
    borrowed_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name="book_borrow_rel",
                                    null=True,
                                    blank=True)
    borrowed_on = models.DateTimeField(_('Creation timestamp'), null=True, blank=True,
                                       auto_now=True)

book_inventory_management/views.py
import json

from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.generic.base import View

from book_inventory_management.book_utils import get_book_details, get_book_borrow_details
from book_inventory_management.models import BookInventoryDetail, BookBorrowDetail


@method_decorator(login_required, name='dispatch')
class BookListView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['book_detail'] = get_book_details()
        context['data_html'] = render_to_string('ajax/book_list.html', request=self.request, context=context)
        if self.request.user.is_superuser:
            context['borrow_detail'] = get_book_borrow_details()
        else:
            context['borrow_detail'] = get_book_borrow_details(user=self.request.user)
        context['borrowed_list'] = render_to_string('ajax/borrowed_list.html', request=self.request, context=context)

        return context

    def dispatch(self, request, *args, **kwargs):
        return super(BookListView, self).dispatch(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class UpdateInventory(View):
    def post(self, request):
        data = {'status': True}
        book_data = {}
        if request.POST.get('slug_val'):
            book_obj = get_book_details(book_id=request.POST.get('slug_val'))
            borrowed_count = book_obj.book_borrowed
            if borrowed_count != book_obj.total_book_count:
                try:
                    with transaction.atomic():
                        borrowed_count += 1
                        book_obj.book_borrowed = borrowed_count
                        book_obj.book_available = book_obj.total_book_count - borrowed_count
                        book_obj.save()
                        BookBorrowDetail.objects.create(
                            borrowed_by=request.user,
                            book=book_obj
                        )
                        book_data['book_detail'] = get_book_details()
                        data['data_html'] = render_to_string('ajax/book_list.html', request=request, context=book_data)
                        if self.request.user.is_superuser:
                            book_data['borrow_detail'] = get_book_borrow_details()
                        else:
                            book_data['borrow_detail'] = get_book_borrow_details(user=self.request.user)
                        data['borrowed_list'] = render_to_string('ajax/borrowed_list.html', request=request,
                                                                 context=book_data)

                except:
                    data['status'] = False
                    data['message'] = 'Something went wrong'
            else:
                data['status'] = False
                data['message'] = 'No book left'
        return HttpResponse(json.dumps(data), content_type="application/json")

book_inventory_management/templates/dashboard.html
{% extends 'base.html' %}
{%load static %}
{%block content%}
            <div class="row">
              <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title mb-0">Book Inventory</h4>
                    <div class="table-responsive book_list">
                    {{data_html}}
                    </div>
                  </div>
                </div>
              </div>
            </div>
<div class="row">
              <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title mb-0">Borrowed Details</h4>
                    <div class="table-responsive book_borrowed_list">
                    {{borrowed_list}}
                    </div>
                  </div>
                </div>
              </div>
            </div>

{%endblock%}

 {% block script %}
<script>
  $(document).on('click','.borrow_book',function(){
    var data = new FormData();
			data.append('csrfmiddlewaretoken',"{{csrf_token}}")
			data.append("slug_val",$(this).attr('data-slug'))
			$.ajax({
							type: "POST",
							url : "{% url 'book_inventory_management:update_inventory' %}",
							data: data,
							processData: false,
							contentType: false,
							success: function(data) {
								if(data.status == true){
									$('.book_list').html(data.data_html );
									$('.book_borrowed_list').html(data.borrowed_list );
									alert('success')
								}
								else{
                                    alert(data.message)
								}
							}
						});


  })
</script>
{% endblock %}